# Generated by Django 4.2.19 on 2025-03-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_platform', '0001_initial'),
    ]

    operations = [
    ]
