# Generated by Django 4.2.19 on 2025-03-03 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_platform', '0003_fileupload_supportticket_supportticketcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('task_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('scheduled_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deletion Task',
                'verbose_name_plural': 'Deletion Tasks',
                'ordering': ['scheduled_date', 'status'],
                'indexes': [models.Index(fields=['user', 'status'], name='gdpr_platfo_user_id_23aed0_idx'), models.Index(fields=['scheduled_date'], name='gdpr_platfo_schedul_763332_idx'), models.Index(fields=['request_id'], name='gdpr_platfo_request_6bdcf6_idx')],
            },
        ),
    ]
