# Generated by Django 4.2.19 on 2025-03-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_platform', '0006_crossbordertransfer_risk_level_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='databreachincident',
            name='status',
            field=models.CharField(choices=[('investigating', 'Investigating'), ('contained', 'Contained'), ('resolved', 'Resolved'), ('monitoring', 'Monitoring')], default='investigating', help_text='Current status of the breach incident', max_length=20),
        ),
    ]
