# Generated by Django 4.2.19 on 2025-03-05 23:17

from django.db import migrations, models
import django.db.models.deletion
import gdpr_platform.models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_platform', '0008_reportschedule_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbreachnotification',
            name='breach',
        ),
        migrations.RemoveField(
            model_name='userbreachnotification',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='databreach',
            options={'ordering': ['-date_reported']},
        ),
        migrations.RemoveField(
            model_name='databreach',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='databreach',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='databreach',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='databreach',
            name='investigation_notes',
        ),
        migrations.RemoveField(
            model_name='databreach',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='databreach',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='databreach',
            name='ai_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databreach',
            name='anomaly_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databreach',
            name='notification_deadline',
            field=models.DateTimeField(default=gdpr_platform.models.get_notification_deadline, help_text='72-hour deadline for notifying supervisory authority'),
        ),
        migrations.AddField(
            model_name='databreach',
            name='resolution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databreach',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databreach',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='breachnotification',
            name='breach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdpr_platform.databreach'),
        ),
        migrations.AlterField(
            model_name='databreach',
            name='containment_measures',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='databreach',
            name='description',
            field=gdpr_platform.models.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='databreach',
            name='lessons_learned',
            field=models.TextField(blank=True, help_text='Post-incident analysis and lessons learned', null=True),
        ),
        migrations.AlterField(
            model_name='databreach',
            name='severity',
            field=models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=20),
        ),
        migrations.DeleteModel(
            name='DataBreachIncident',
        ),
        migrations.DeleteModel(
            name='UserBreachNotification',
        ),
    ]
