# Generated by Django 4.2.19 on 2025-03-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_platform', '0010_alter_breachnotification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breachnotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
